name: Grade Submission

on:
  pull_request:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout participant code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas scikit-learn

      - name: Write secret labels to file
        run: echo "${{ secrets.TEST_LABELS }}" > grader/test_labels.csv

      - name: Check submission file exists
        run: |
          count=$(find submission/ -name "*submission.csv" | wc -l)
          if [ "$count" -eq 0 ]; then
            echo "❌ No submission file found in submission/ folder!"
            echo "   Name your file like: group1_submission.csv, team5_submission.csv"
            exit 1
          fi
          echo "✅ Found $count submission file(s)"

      - name: Run grader
        run: python grader/grader.py
